### ISSUE TITLE
etcd as the backend, prefix option will overwrite prefix item in template file in version 0.12

### ISSUE THREAD

**Issue by danielzhanghl** [bacongobbler/confd#3]
this is an issue I reported to Kelsey Hightower' CONFD, but it seems not active any more, and report here,
https://github.com/kelseyhightower/confd/issues/516

highlight of the issue:
---------------
it's a change on the new version, the prefix is not a joint one, instead, the prefix in template file will be overwritten by confd profile, which cause the configuration file failed with this new version. 
code as below:

resource.go:
NewTemplateResource, new version:

    if config.Prefix != "" {
            // tr.Prefix = config.Prefix
            if tr.Prefix == "" {
                    tr.Prefix = config.Prefix

but in previews version, it's a joint prefix as below:
    tr.prefix = filepath.Join("/", config.Prefix, tr.Prefix)

**Comment by bacongobbler** [comment]
I'm no longer maintaining this fork. Please make the change upstream. There are new maintainers taking over development of confd so this fork is no longer needed.

**Comment by NStanleyZhang** [comment]
could you let us know which one should i follow up?

**Comment by bacongobbler** [comment]
upstream is at https://github.com/kelseyhightower/confd.
