### ISSUE TITLE
Missed updates with etcdv2 backend

### ISSUE THREAD

**Issue by robbrockbank** [bacongobbler/confd#4]
After upgrading my confd from v0.10.0 to v0.12.0, I seem to be hitting issues where some of the files created by the template do not contain the latest contents of etcd - it looks as though it's missing an update.

We have quite a lot of different templates monitoring a bunch of different prefixes and so there are quite a few updates going on.

Do you have recommendation of how best to diagnose/investigate this, and whether any changes between v0.10.0 and v0.12.1 leap out that might be the cause of these missed updates?

**Comment by bacongobbler** [comment]
Yes, check out the master branch and you can diff/compare against Kelsey's master branch.

**Comment by HeavyHorst** [comment]
We switched from the deprecated etcd client lib to the new one.

**Comment by bacongobbler** [comment]
I'm no longer maintaining this fork. Please make the change upstream. There are new maintainers taking over development of confd so this fork is no longer needed.
